name: Build & Release Package

on:
  push:
    tags:
      - v**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: zip -r MemeSounds.zip BepInEx README.md icon.png manifest.json
      - uses: actions/upload-artifact@v4
        with:
            name: ${{ github.ref_name }}
            path: MemeSounds.zip
      - uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          namespace: Gassayping
          description: Replaces enemies' sounds with sounds from memes.
          token: ${{ secrets.THUNDERSTORE_API_TOKEN }}
          name: MemeSounds
          version: ${{ github.ref_name }}
          community: repo
          file: MemeSounds.zip
          repo: thunderstore.io
          categories: |
            audio
            monsters
            clientside
            misc

