name: Build & Release Package

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: zip -r MemeSounds.zip BepInEx README.md icon.png manifest.json
      - uses: actions/upload-artifact@v4
        with:
            name: ${{ inputs.version }}
            path: MemeSounds.zip
      - uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          namespace: Gassayping
          description: Replaces enemies' sounds with sounds from memes.
          token: ${{ secrets.THUNDERSTORE_API_TOKEN }}
          name: MemeSounds
          version: ${{ inputs.version }}
          community: repo
          file: MemeSounds.zip
          categories: |
            audio
            monsters
            clientside
            misc

